language: minimal
dist: bionic
sudo: required

branches:
  only:
  - master

services:
- docker

install:
- docker build --tag amp .

matrix:
  include:
  - name: "Integration Tests"
    before_script:
    - docker run -d --name=redis --network=host redis:5-alpine --requirepass 'CHANGE ME!!'
    script:
    - docker run --rm --network=host --entrypoint="" amp pipenv run test-all
    after_script:
    - docker rm -f redis
  - name: "Lint and Type Checking"
    script:
    - docker run --rm --entrypoint="" amp pipenv run lint
